import type { SVGProps } from 'react';

export function MarchSvg({ width = 200, height = 200, viewBox = '0 0 200 200', ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox={viewBox}
      xmlns="http://www.w3.org/2000/svg"
      width={width}
      height={height}
      {...props}
    >
      <defs>
        <clipPath id="mr">
          <rect
            width="200"
            height="200"
            rx="20"
          />
        </clipPath>
      </defs>
      <g clipPath="url(#mr)">
        <rect
          width="200"
          height="200"
          fill="#b5cad8"
        />
        <rect
          width="200"
          height="100"
          fill="#a8c0d0"
        />
        <ellipse
          cx="50"
          cy="50"
          rx="40"
          ry="15"
          fill="#c8d8e4"
          opacity=".8"
        />
        <ellipse
          cx="140"
          cy="40"
          rx="50"
          ry="18"
          fill="#d4e0ea"
          opacity=".7"
        />
        <ellipse
          cx="100"
          cy="65"
          rx="60"
          ry="14"
          fill="#dce6ee"
          opacity=".6"
        />
        <path
          d="M0 90 Q40 85 80 92 T160 95 T200 90 V120 H0 Z"
          fill="#6b8050"
        />
        <path
          d="M0 105 Q40 100 80 105 T200 108 V200 H0 Z"
          fill="#5a4030"
        />
        <path
          d="M0 105 L200 105 L200 200 L0 200 Z"
          fill="#6b4f33"
        />
        <path
          d="M20 110 Q40 108 60 112 Q80 108 100 112 T160 114 T200 112"
          stroke="#4a3525"
          strokeWidth="2"
          fill="none"
          opacity=".5"
        />
        <ellipse
          cx="40"
          cy="110"
          rx="35"
          ry="8"
          fill="#e8eef4"
        />
        <ellipse
          cx="160"
          cy="115"
          rx="40"
          ry="9"
          fill="#e8eef4"
        />
        <ellipse
          cx="100"
          cy="108"
          rx="20"
          ry="5"
          fill="#e8eef4"
        />
        <g transform="translate(85 145)">
          <path
            d="M0 0 Q-2 15 0 30"
            stroke="#4a7028"
            strokeWidth="2"
            fill="none"
          />
          <path
            d="M-3 12 Q-8 18 -2 20"
            stroke="#4a7028"
            strokeWidth="1.5"
            fill="none"
          />
          <ellipse
            cx="0"
            cy="-2"
            rx="3"
            ry="6"
            fill="#ffffff"
          />
          <ellipse
            cx="-3"
            cy="0"
            rx="2"
            ry="5"
            fill="#f0f6fc"
          />
          <ellipse
            cx="3"
            cy="0"
            rx="2"
            ry="5"
            fill="#f0f6fc"
          />
          <circle
            cx="0"
            cy="2"
            r="1.5"
            fill="#e8c040"
          />
        </g>
        <g transform="translate(105 150)">
          <path
            d="M0 0 Q1 12 0 25"
            stroke="#4a7028"
            strokeWidth="2"
            fill="none"
          />
          <ellipse
            cx="0"
            cy="-2"
            rx="3"
            ry="5"
            fill="#ffffff"
          />
          <ellipse
            cx="-3"
            cy="0"
            rx="2"
            ry="4"
            fill="#f0f6fc"
          />
          <ellipse
            cx="3"
            cy="0"
            rx="2"
            ry="4"
            fill="#f0f6fc"
          />
          <circle
            cx="0"
            cy="2"
            r="1.2"
            fill="#e8c040"
          />
        </g>
        <g transform="translate(125 148)">
          <path
            d="M0 0 Q-1 14 0 28"
            stroke="#4a7028"
            strokeWidth="2"
            fill="none"
          />
          <path
            d="M2 10 Q6 14 1 18"
            stroke="#4a7028"
            strokeWidth="1.3"
            fill="none"
          />
          <ellipse
            cx="0"
            cy="-2"
            rx="3"
            ry="5"
            fill="#ffffff"
          />
          <ellipse
            cx="-3"
            cy="0"
            rx="2"
            ry="4"
            fill="#f0f6fc"
          />
          <ellipse
            cx="3"
            cy="0"
            rx="2"
            ry="4"
            fill="#f0f6fc"
          />
          <circle
            cx="0"
            cy="2"
            r="1.2"
            fill="#e8c040"
          />
        </g>
        <g transform="translate(40 155)">
          <path
            d="M0 0 Q1 10 0 22"
            stroke="#4a7028"
            strokeWidth="1.8"
            fill="none"
          />
          <ellipse
            cx="0"
            cy="-2"
            rx="2.5"
            ry="4"
            fill="#ffffff"
          />
          <ellipse
            cx="-2.5"
            cy="0"
            rx="1.8"
            ry="3.5"
            fill="#f0f6fc"
          />
          <ellipse
            cx="2.5"
            cy="0"
            rx="1.8"
            ry="3.5"
            fill="#f0f6fc"
          />
        </g>
        <g
          stroke="#5a7028"
          strokeWidth="1"
          fill="none"
        >
          <path d="M65 165 Q66 160 67 165" />
          <path d="M150 168 Q151 162 152 168" />
          <path d="M175 175 Q176 170 177 175" />
          <path d="M25 175 Q26 170 27 175" />
        </g>
        <g
          stroke="#7a9fc8"
          strokeWidth="0.8"
          opacity=".5"
          strokeLinecap="round"
        >
          <line
            x1="60"
            y1="20"
            x2="58"
            y2="32"
          />
          <line
            x1="120"
            y1="15"
            x2="118"
            y2="28"
          />
          <line
            x1="170"
            y1="25"
            x2="168"
            y2="38"
          />
          <line
            x1="30"
            y1="35"
            x2="28"
            y2="47"
          />
        </g>
      </g>
    </svg>
  );
}
