import type { SVGProps } from 'react';

export function NovemberSvg({ width = 200, height = 200, viewBox = '0 0 200 200', ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox={viewBox}
      xmlns="http://www.w3.org/2000/svg"
      width={width}
      height={height}
      {...props}
    >
      <defs>
        <clipPath id="nv">
          <rect
            width={width}
            height={height}
            rx="20"
          />
        </clipPath>
      </defs>
      <g clip-path="url(#nv)">
        <rect
          width={width}
          height={height}
          fill="#8a8a8a"
        />
        <rect
          width={width}
          height="115"
          fill="#9a9a9a"
        />
        <ellipse
          cx="100"
          cy="60"
          rx="120"
          ry="20"
          fill="#b8b8b8"
          opacity=".7"
        />
        <ellipse
          cx="50"
          cy="80"
          rx="60"
          ry="15"
          fill="#c8c8c8"
          opacity=".6"
        />
        <ellipse
          cx="150"
          cy="85"
          rx="65"
          ry="14"
          fill="#c8c8c8"
          opacity=".6"
        />
        <path
          d="M0 115 Q40 110 80 115 T200 118 V200 H0 Z"
          fill="#5a4525"
        />
        <path
          d="M0 135 L200 135 L200 200 L0 200 Z"
          fill="#4a3520"
        />
        <ellipse
          cx="60"
          cy="115"
          rx="40"
          ry="6"
          fill="#3a2818"
          opacity=".5"
        />
        <ellipse
          cx="150"
          cy="120"
          rx="45"
          ry="7"
          fill="#3a2818"
          opacity=".5"
        />
        <ellipse
          cx="100"
          cy="130"
          rx="35"
          ry="5"
          fill="#7a8090"
          opacity=".5"
        />
        <g transform="translate(45 115)">
          <line
            x1="0"
            y1="0"
            x2="0"
            y2="-58"
            stroke="#3a2510"
            stroke-width="3.5"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-15"
            x2="-18"
            y2="-28"
            stroke="#3a2510"
            stroke-width="2"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-22"
            x2="14"
            y2="-35"
            stroke="#3a2510"
            stroke-width="2"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-32"
            x2="-15"
            y2="-42"
            stroke="#3a2510"
            stroke-width="1.8"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-38"
            x2="12"
            y2="-48"
            stroke="#3a2510"
            stroke-width="1.8"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-45"
            x2="-8"
            y2="-55"
            stroke="#3a2510"
            stroke-width="1.5"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-48"
            x2="8"
            y2="-58"
            stroke="#3a2510"
            stroke-width="1.5"
            stroke-linecap="round"
          />
          <line
            x1="-18"
            y1="-28"
            x2="-25"
            y2="-35"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="-18"
            y1="-28"
            x2="-22"
            y2="-22"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="14"
            y1="-35"
            x2="22"
            y2="-40"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="14"
            y1="-35"
            x2="18"
            y2="-30"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="-15"
            y1="-42"
            x2="-20"
            y2="-48"
            stroke="#3a2510"
            stroke-width="1"
            stroke-linecap="round"
          />
          <line
            x1="12"
            y1="-48"
            x2="18"
            y2="-52"
            stroke="#3a2510"
            stroke-width="1"
            stroke-linecap="round"
          />
          <line
            x1="-8"
            y1="-55"
            x2="-12"
            y2="-60"
            stroke="#3a2510"
            stroke-width="0.8"
            stroke-linecap="round"
          />
          <line
            x1="8"
            y1="-58"
            x2="12"
            y2="-62"
            stroke="#3a2510"
            stroke-width="0.8"
            stroke-linecap="round"
          />
        </g>
        <g transform="translate(150 118)">
          <line
            x1="0"
            y1="0"
            x2="0"
            y2="-50"
            stroke="#3a2510"
            stroke-width="3"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-13"
            x2="-15"
            y2="-25"
            stroke="#3a2510"
            stroke-width="1.8"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-20"
            x2="13"
            y2="-32"
            stroke="#3a2510"
            stroke-width="1.8"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-28"
            x2="-13"
            y2="-38"
            stroke="#3a2510"
            stroke-width="1.5"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-35"
            x2="11"
            y2="-44"
            stroke="#3a2510"
            stroke-width="1.5"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-42"
            x2="-7"
            y2="-50"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="-15"
            y1="-25"
            x2="-22"
            y2="-30"
            stroke="#3a2510"
            stroke-width="1"
            stroke-linecap="round"
          />
          <line
            x1="13"
            y1="-32"
            x2="20"
            y2="-36"
            stroke="#3a2510"
            stroke-width="1"
            stroke-linecap="round"
          />
          <line
            x1="-13"
            y1="-38"
            x2="-18"
            y2="-44"
            stroke="#3a2510"
            stroke-width="0.9"
            stroke-linecap="round"
          />
          <line
            x1="11"
            y1="-44"
            x2="17"
            y2="-48"
            stroke="#3a2510"
            stroke-width="0.9"
            stroke-linecap="round"
          />
        </g>
        <g transform="translate(110 115)">
          <line
            x1="0"
            y1="0"
            x2="0"
            y2="-38"
            stroke="#3a2510"
            stroke-width="2.5"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-12"
            x2="-12"
            y2="-22"
            stroke="#3a2510"
            stroke-width="1.5"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-18"
            x2="10"
            y2="-26"
            stroke="#3a2510"
            stroke-width="1.5"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-26"
            x2="-10"
            y2="-32"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-30"
            x2="9"
            y2="-36"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="-12"
            y1="-22"
            x2="-17"
            y2="-26"
            stroke="#3a2510"
            stroke-width="0.9"
            stroke-linecap="round"
          />
          <line
            x1="10"
            y1="-26"
            x2="16"
            y2="-30"
            stroke="#3a2510"
            stroke-width="0.9"
            stroke-linecap="round"
          />
        </g>
        <g transform="translate(180 120)">
          <line
            x1="0"
            y1="0"
            x2="0"
            y2="-32"
            stroke="#3a2510"
            stroke-width="2"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-10"
            x2="-10"
            y2="-18"
            stroke="#3a2510"
            stroke-width="1.3"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-15"
            x2="9"
            y2="-22"
            stroke="#3a2510"
            stroke-width="1.3"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-22"
            x2="-8"
            y2="-28"
            stroke="#3a2510"
            stroke-width="1"
            stroke-linecap="round"
          />
        </g>
        <g transform="translate(18 117)">
          <line
            x1="0"
            y1="0"
            x2="0"
            y2="-28"
            stroke="#3a2510"
            stroke-width="2"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-8"
            x2="-8"
            y2="-15"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-13"
            x2="7"
            y2="-19"
            stroke="#3a2510"
            stroke-width="1.2"
            stroke-linecap="round"
          />
        </g>
        <g transform="translate(78 117)">
          <line
            x1="0"
            y1="0"
            x2="0"
            y2="-30"
            stroke="#3a2510"
            stroke-width="2.2"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-9"
            x2="-9"
            y2="-17"
            stroke="#3a2510"
            stroke-width="1.3"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-15"
            x2="8"
            y2="-22"
            stroke="#3a2510"
            stroke-width="1.3"
            stroke-linecap="round"
          />
          <line
            x1="0"
            y1="-22"
            x2="-7"
            y2="-27"
            stroke="#3a2510"
            stroke-width="1"
            stroke-linecap="round"
          />
        </g>
        <ellipse
          cx="100"
          cy="100"
          rx="180"
          ry="15"
          fill="#b8b8b8"
          opacity=".5"
        />
        <g
          fill="#7a8090"
          opacity=".5"
        >
          <ellipse
            cx="30"
            cy="148"
            rx="8"
            ry="2"
          />
          <ellipse
            cx="80"
            cy="155"
            rx="12"
            ry="2.5"
          />
          <ellipse
            cx="135"
            cy="150"
            rx="10"
            ry="2"
          />
          <ellipse
            cx="175"
            cy="158"
            rx="9"
            ry="2"
          />
          <ellipse
            cx="50"
            cy="170"
            rx="14"
            ry="3"
          />
          <ellipse
            cx="160"
            cy="175"
            rx="11"
            ry="2.5"
          />
        </g>
        <g fill="#3a2818">
          <ellipse
            cx="35"
            cy="125"
            rx="2"
            ry="1.2"
            transform="rotate(20 35 125)"
          />
          <ellipse
            cx="95"
            cy="128"
            rx="2"
            ry="1.2"
            transform="rotate(-30 95 128)"
          />
          <ellipse
            cx="135"
            cy="125"
            rx="2"
            ry="1.2"
            transform="rotate(45 135 125)"
          />
          <ellipse
            cx="175"
            cy="128"
            rx="2"
            ry="1.2"
            transform="rotate(-15 175 128)"
          />
        </g>
      </g>
    </svg>
  );
}
