import type { SVGProps } from 'react';

export function OctoberSvg({ width = 200, height = 200, viewBox = '0 0 200 200', ...props }: SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={viewBox}
      width={width}
      height={height}
      {...props}
    >
      <defs>
        <clipPath id="oc">
          <rect
            width={width}
            height={height}
            rx="20"
          />
        </clipPath>
      </defs>
      <g clipPath="url(#oc)">
        <rect
          width={width}
          height={height}
          fill="#d8c890"
        />
        <rect
          width={width}
          height="105"
          fill="#e8d0a0"
        />
        <ellipse
          cx="60"
          cy="35"
          rx="30"
          ry="12"
          fill="#f5e0b0"
          opacity=".9"
        />
        <ellipse
          cx="150"
          cy="45"
          rx="35"
          ry="13"
          fill="#f5e0b0"
          opacity=".85"
        />
        <path
          d="M0 105 Q40 100 80 105 T160 108 T200 105 V200 H0 Z"
          fill="#b08840"
        />
        <path
          d="M0 125 Q40 120 80 125 T200 128 V200 H0 Z"
          fill="#906820"
        />
        <path
          d="M0 150 L200 150 L200 200 L0 200 Z"
          fill="#7a4820"
        />
        <g transform="translate(50 95)">
          <rect
            x="-3.5"
            y="0"
            width="7"
            height="35"
            fill="#4a3015"
          />
          <line
            x1="-3.5"
            y1="8"
            x2="-3.5"
            y2="32"
            stroke="#2d1808"
            strokeWidth="0.4"
          />
          <line
            x1="0"
            y1="5"
            x2="0"
            y2="34"
            stroke="#2d1808"
            strokeWidth="0.4"
          />
          <line
            x1="3.5"
            y1="10"
            x2="3.5"
            y2="33"
            stroke="#2d1808"
            strokeWidth="0.4"
          />
          <ellipse
            cx="0"
            cy="-12"
            rx="32"
            ry="28"
            fill="#c84020"
          />
          <ellipse
            cx="-15"
            cy="-22"
            rx="14"
            ry="12"
            fill="#e85820"
          />
          <ellipse
            cx="15"
            cy="-20"
            rx="15"
            ry="13"
            fill="#a82010"
          />
          <ellipse
            cx="0"
            cy="-30"
            rx="13"
            ry="11"
            fill="#f06030"
          />
          <ellipse
            cx="-22"
            cy="-8"
            rx="12"
            ry="10"
            fill="#d84818"
          />
          <ellipse
            cx="22"
            cy="-5"
            rx="11"
            ry="9"
            fill="#b83018"
          />
          <ellipse
            cx="-8"
            cy="-18"
            rx="9"
            ry="7"
            fill="#e85020"
          />
          <ellipse
            cx="8"
            cy="-15"
            rx="10"
            ry="8"
            fill="#c84020"
          />
          <g
            fill="#8a2010"
            opacity=".6"
          >
            <circle
              cx="-18"
              cy="-25"
              r="1.5"
            />
            <circle
              cx="-12"
              cy="-15"
              r="1.5"
            />
            <circle
              cx="-25"
              cy="-12"
              r="1.5"
            />
            <circle
              cx="-20"
              cy="-3"
              r="1.2"
            />
            <circle
              cx="-5"
              cy="-25"
              r="1.5"
            />
            <circle
              cx="12"
              cy="-23"
              r="1.5"
            />
            <circle
              cx="18"
              cy="-12"
              r="1.5"
            />
            <circle
              cx="20"
              cy="0"
              r="1.2"
            />
            <circle
              cx="5"
              cy="-20"
              r="1.5"
            />
            <circle
              cx="2"
              cy="-32"
              r="1.2"
            />
          </g>
        </g>
        <g transform="translate(140 100)">
          <rect
            x="-3"
            y="0"
            width="6"
            height="30"
            fill="#4a3015"
          />
          <ellipse
            cx="0"
            cy="-10"
            rx="28"
            ry="24"
            fill="#e89020"
          />
          <ellipse
            cx="-12"
            cy="-18"
            rx="12"
            ry="10"
            fill="#f5b040"
          />
          <ellipse
            cx="12"
            cy="-16"
            rx="13"
            ry="11"
            fill="#c87020"
          />
          <ellipse
            cx="0"
            cy="-26"
            rx="11"
            ry="9"
            fill="#f5a020"
          />
          <ellipse
            cx="-18"
            cy="-5"
            rx="10"
            ry="8"
            fill="#d88030"
          />
          <ellipse
            cx="18"
            cy="-3"
            rx="10"
            ry="8"
            fill="#b85820"
          />
          <ellipse
            cx="-5"
            cy="-15"
            rx="8"
            ry="6"
            fill="#f5a830"
          />
          <ellipse
            cx="7"
            cy="-12"
            rx="9"
            ry="7"
            fill="#d88820"
          />
          <g
            fill="#a05010"
            opacity=".6"
          >
            <circle
              cx="-15"
              cy="-20"
              r="1.3"
            />
            <circle
              cx="-10"
              cy="-12"
              r="1.3"
            />
            <circle
              cx="-20"
              cy="-8"
              r="1.3"
            />
            <circle
              cx="-3"
              cy="-22"
              r="1.3"
            />
            <circle
              cx="10"
              cy="-20"
              r="1.3"
            />
            <circle
              cx="15"
              cy="-10"
              r="1.3"
            />
            <circle
              cx="20"
              cy="0"
              r="1.3"
            />
            <circle
              cx="0"
              cy="-28"
              r="1.3"
            />
          </g>
        </g>
        <g transform="translate(180 110)">
          <rect
            x="-2"
            y="0"
            width="4"
            height="20"
            fill="#4a3015"
          />
          <ellipse
            cx="0"
            cy="-6"
            rx="15"
            ry="13"
            fill="#c83018"
          />
          <ellipse
            cx="-6"
            cy="-10"
            rx="7"
            ry="6"
            fill="#e85020"
          />
          <ellipse
            cx="7"
            cy="-8"
            rx="7"
            ry="6"
            fill="#a82010"
          />
          <ellipse
            cx="0"
            cy="-14"
            rx="6"
            ry="5"
            fill="#f06030"
          />
        </g>
        <g transform="translate(15 110)">
          <rect
            x="-2"
            y="0"
            width="4"
            height="18"
            fill="#4a3015"
          />
          <ellipse
            cx="0"
            cy="-5"
            rx="13"
            ry="11"
            fill="#e8a020"
          />
          <ellipse
            cx="-5"
            cy="-9"
            rx="6"
            ry="5"
            fill="#f5b840"
          />
          <ellipse
            cx="6"
            cy="-7"
            rx="6"
            ry="5"
            fill="#c87018"
          />
        </g>
        <ellipse
          cx="20"
          cy="145"
          rx="5"
          ry="3"
          fill="#e85020"
          transform="rotate(30 20 145)"
        />
        <path
          d="M70 158 Q65 154 67 160 Q65 162 70 162 Q75 162 73 160 Q75 154 70 158"
          fill="#c83018"
        />
        <ellipse
          cx="105"
          cy="162"
          rx="5"
          ry="3"
          fill="#e89020"
          transform="rotate(-20 105 162)"
        />
        <path
          d="M125 155 Q120 151 122 157 Q120 159 125 159 Q130 159 128 157 Q130 151 125 155"
          fill="#f5a030"
        />
        <ellipse
          cx="160"
          cy="168"
          rx="5"
          ry="3"
          fill="#a82010"
          transform="rotate(45 160 168)"
        />
        <ellipse
          cx="180"
          cy="175"
          rx="4"
          ry="2.5"
          fill="#c87020"
          transform="rotate(60 180 175)"
        />
        <ellipse
          cx="45"
          cy="175"
          rx="4"
          ry="2.5"
          fill="#e85020"
          transform="rotate(-40 45 175)"
        />
        <path
          d="M90 182 Q86 179 87 183 Q86 185 90 185 Q94 185 93 183 Q94 179 90 182"
          fill="#d88030"
        />
        <ellipse
          cx="35"
          cy="60"
          rx="3"
          ry="2"
          fill="#e85020"
          transform="rotate(45 35 60)"
          opacity=".7"
        />
        <ellipse
          cx="105"
          cy="75"
          rx="3"
          ry="2"
          fill="#e89020"
          transform="rotate(20 105 75)"
          opacity=".7"
        />
      </g>
    </svg>
  );
}
