import type { SVGProps } from 'react';

export function SeptemberSvg({
  width = 200,
  height = 200,
  viewBox = '0 0 200 200',
  ...props
}: SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox={viewBox}
      xmlns="http://www.w3.org/2000/svg"
      style="width:100%;height:auto;border-radius:16px"
      {...props}
    >
      <defs>
        <clipPath id="sp2">
          <rect
            width={width}
            height={height}
            rx="20"
          />
        </clipPath>
      </defs>
      <g clip-path="url(#sp2)">
        <rect
          width={width}
          height={height}
          fill="#8ab8d0"
        />
        <rect
          width={width}
          height="110"
          fill="#9ac8d8"
        />
        <ellipse
          cx="40"
          cy="35"
          rx="25"
          ry="11"
          fill="#ffffff"
          opacity=".85"
        />
        <ellipse
          cx="25"
          cy="40"
          rx="15"
          ry="9"
          fill="#ffffff"
          opacity=".85"
        />
        <ellipse
          cx="155"
          cy="50"
          rx="22"
          ry="10"
          fill="#ffffff"
          opacity=".8"
        />
        <ellipse
          cx="175"
          cy="45"
          rx="14"
          ry="8"
          fill="#ffffff"
          opacity=".8"
        />
        <path
          d="M0 110 Q40 105 80 110 T160 112 T200 110 V200 H0 Z"
          fill="#88a850"
        />
        <path
          d="M0 125 Q40 120 80 125 T200 128 V200 H0 Z"
          fill="#789838"
        />
        <g transform="translate(100 90)">
          <rect
            x="-4"
            y="0"
            width="8"
            height="40"
            fill="#5a3520"
          />
          <line
            x1="-4"
            y1="10"
            x2="-4"
            y2="35"
            stroke="#3d2010"
            stroke-width="0.5"
          />
          <line
            x1="0"
            y1="5"
            x2="0"
            y2="38"
            stroke="#3d2010"
            stroke-width="0.5"
          />
          <line
            x1="4"
            y1="8"
            x2="4"
            y2="36"
            stroke="#3d2010"
            stroke-width="0.5"
          />
          <ellipse
            cx="0"
            cy="-15"
            rx="40"
            ry="32"
            fill="#4a8020"
          />
          <ellipse
            cx="-20"
            cy="-25"
            rx="18"
            ry="15"
            fill="#7aa830"
          />
          <ellipse
            cx="20"
            cy="-22"
            rx="20"
            ry="16"
            fill="#c8a830"
          />
          <ellipse
            cx="-15"
            cy="-10"
            rx="15"
            ry="12"
            fill="#88a830"
          />
          <ellipse
            cx="15"
            cy="-8"
            rx="14"
            ry="11"
            fill="#d8a020"
          />
          <ellipse
            cx="0"
            cy="-35"
            rx="16"
            ry="13"
            fill="#a8b830"
          />
          <ellipse
            cx="-30"
            cy="-15"
            rx="12"
            ry="10"
            fill="#5a9020"
          />
          <ellipse
            cx="30"
            cy="-12"
            rx="13"
            ry="11"
            fill="#e89020"
          />
          <ellipse
            cx="-8"
            cy="-20"
            rx="10"
            ry="8"
            fill="#88a020"
          />
          <ellipse
            cx="8"
            cy="-18"
            rx="11"
            ry="9"
            fill="#d8a830"
          />
          <g
            fill="#3a6818"
            opacity=".7"
          >
            <circle
              cx="-22"
              cy="-30"
              r="1.5"
            />
            <circle
              cx="-15"
              cy="-15"
              r="1.5"
            />
            <circle
              cx="-30"
              cy="-10"
              r="1.5"
            />
            <circle
              cx="-25"
              cy="-22"
              r="1.2"
            />
            <circle
              cx="-5"
              cy="-32"
              r="1.5"
            />
            <circle
              cx="-12"
              cy="-25"
              r="1.2"
            />
          </g>
          <g
            fill="#a07820"
            opacity=".7"
          >
            <circle
              cx="22"
              cy="-28"
              r="1.5"
            />
            <circle
              cx="15"
              cy="-12"
              r="1.5"
            />
            <circle
              cx="28"
              cy="-7"
              r="1.5"
            />
            <circle
              cx="25"
              cy="-18"
              r="1.2"
            />
            <circle
              cx="8"
              cy="-30"
              r="1.5"
            />
            <circle
              cx="12"
              cy="-22"
              r="1.2"
            />
          </g>
        </g>
        <g transform="translate(35 140)">
          <ellipse
            cx="0"
            cy="0"
            rx="5"
            ry="3"
            fill="#e89020"
            transform="rotate(30)"
          />
        </g>
        <g transform="translate(60 155)">
          <ellipse
            cx="0"
            cy="0"
            rx="5"
            ry="3"
            fill="#c87020"
            transform="rotate(-20)"
          />
        </g>
        <g transform="translate(140 150)">
          <path
            d="M0 0 Q-4 -3 -3 1 Q-4 3 0 3 Q4 3 3 1 Q4 -3 0 0"
            fill="#d8a020"
          />
        </g>
        <g transform="translate(170 160)">
          <ellipse
            cx="0"
            cy="0"
            rx="5"
            ry="3"
            fill="#a05020"
            transform="rotate(45)"
          />
        </g>
        <g transform="translate(160 175)">
          <ellipse
            cx="0"
            cy="0"
            rx="4"
            ry="2.5"
            fill="#e8a030"
            transform="rotate(10)"
          />
        </g>
        <g transform="translate(45 175)">
          <path
            d="M0 0 Q-4 -3 -3 1 Q-4 3 0 3 Q4 3 3 1 Q4 -3 0 0"
            fill="#c87020"
          />
        </g>
        <g transform="translate(80 168)">
          <ellipse
            cx="0"
            cy="0"
            rx="4"
            ry="2.5"
            fill="#d8a020"
            transform="rotate(-30)"
          />
        </g>
        <g transform="translate(120 178)">
          <path
            d="M0 0 Q-4 -3 -3 1 Q-4 3 0 3 Q4 3 3 1 Q4 -3 0 0"
            fill="#a05020"
          />
        </g>
        <g transform="translate(15 165)">
          <ellipse
            cx="0"
            cy="0"
            rx="4"
            ry="2.5"
            fill="#e89020"
            transform="rotate(60)"
          />
        </g>
        <g transform="translate(185 145)">
          <ellipse
            cx="0"
            cy="0"
            rx="3"
            ry="2"
            fill="#d8a020"
            transform="rotate(20)"
          />
        </g>
        <g transform="translate(25 100)">
          <ellipse
            cx="0"
            cy="0"
            rx="3"
            ry="2"
            fill="#e8a030"
            transform="rotate(45)"
            opacity=".7"
          />
        </g>
        <g transform="translate(155 85)">
          <ellipse
            cx="0"
            cy="0"
            rx="3"
            ry="2"
            fill="#c87020"
            transform="rotate(-30)"
            opacity=".7"
          />
        </g>
      </g>
    </svg>
  );
}
