export const MOCK_ALL_CATEGORIES = [
  {
    id: 1,
    category: 'groceries',
    subtitle: 'Закупка в АТБ',
    title: 'Expense',
    type: 'expense' as const,
    amount: '850',
    date: new Date(),
  },
  {
    id: 2,
    category: 'housing',
    subtitle: 'Оренда квартири',
    title: 'Expense',
    type: 'expense' as const,
    amount: '12000',
    date: new Date(),
  },
  {
    id: 3,
    category: 'utilities',
    subtitle: 'Оплата за світло та воду',
    title: 'Expense',
    type: 'expense' as const,
    amount: '1500',
    date: new Date(),
  },
  {
    id: 4,
    category: 'transport',
    subtitle: 'Проїзд у метро та таксі',
    title: 'Expense',
    type: 'expense' as const,
    amount: '400',
    date: new Date(),
  },
  {
    id: 5,
    category: 'entertainment',
    subtitle: 'Квитки в кіно',
    title: 'Expense',
    type: 'expense' as const,
    amount: '300',
    date: new Date(),
  },
  {
    id: 6,
    category: 'education',
    subtitle: 'Курс по Next.js',
    title: 'Expense',
    type: 'expense' as const,
    amount: '2500',
    date: new Date(),
  },
  {
    id: 7,
    category: 'shopping',
    subtitle: 'Нова футболка',
    title: 'Expense',
    type: 'expense' as const,
    amount: '600',
    date: new Date(),
  },
  {
    id: 8,
    category: 'health',
    subtitle: 'Вітаміни',
    title: 'Expense',
    type: 'expense' as const,
    amount: '450',
    date: new Date(),
  },
  {
    id: 9,
    category: 'misc',
    subtitle: 'Якась дрібниця',
    title: 'Expense',
    type: 'expense' as const,
    amount: '100',
    date: new Date(),
  },

  // --- ДОХОДИ (Incomes) ---
  {
    id: 10,
    category: 'salary',
    subtitle: 'Виплата за березень',
    title: 'Income',
    type: 'income' as const,
    amount: '25000',
    date: new Date(),
  },
  {
    id: 11,
    category: 'investments',
    subtitle: 'Дивіденди',
    title: 'Income',
    type: 'income' as const,
    amount: '1200',
    date: new Date(),
  },
  {
    id: 12,
    category: 'freelance',
    subtitle: 'Лендінг для клієнта',
    title: 'Income',
    type: 'income' as const,
    amount: '8000',
    date: new Date(),
  },
  {
    id: 13,
    category: 'scholarship',
    subtitle: 'Підвищена стипендія',
    title: 'Income',
    type: 'income' as const,
    amount: '2900',
    date: new Date(),
  },
];
