name: Next.js Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Next.js Build
        run: npm run build
        env:
          DB_HOST: "localhost"
          DB_PORT: "5432"
          DB_USERNAME: "finman"
          DB_PASSWORD: "finman"
          DB_DATABASE: "finman"
          JWT_SECRET: "your_super_wwwwww_key_at_least_32_characters_long"
          NEXT_PUBLIC_API_URL: "http://localhost:3000"
          RESEND_FROM: "noreply@yourdomain"
          RESEND_API_KEY: "your_resend_api_key"
